### ISSUE TITLE
Depth

### ISSUE THREAD

**Issue by Fannzi** [surgical-vision/servcttk#5]
Hi ,thanks for the great work.
You mentioned that the depth images was "mm depth for each pixel scaled by 256 and stored as 16 bit PNG", take 31000 for a pixel in the uint16 PNG image, the corresponding depth to that pixel should be 31000/65536 *256=121.09mm?

**Comment by EddiePJEdwards** [comment]
Yes - that's right. In the scripts we tend to simply this by just dividing by 256.0

Thank you for your interest in this dataset.
